version: '3.8'

services:
  app:
    build: .
    container_name: meu_app
    ports:
      - "3095:3095"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: meu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: meu_banco
    ports:
      - "3306:3306"
